# Generated by Django 4.0 on 2021-12-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='gitlab_url',
        ),
    ]
